### ISSUE TITLE
关于实验结果的问题

### ISSUE THREAD

**Issue by huangkaiyu** [hankcs/multi-criteria-cws#12]
您好，我最近在做相关工作，想引用您的文章，但是在文章中没有看到OOV的召回率的结果，我十分需要这部分结果，目前由于不可抗力原因可能无法复现模型，看到您是使用的官方脚本程序，那应该对OOV的召回率也有输出，可否提供给我一份OOV的召回率结果呢

**Comment by hankcs** [comment]
您好，非常抱歉，时间过去太久当时的模型和日志没有保留下来。但在CPU上跑完最耗时的实验应该在一周左右，不算太难。

**Comment by huangkaiyu** [comment]
十分感谢您的回复，我会尝试尽可能复现您的结果，如有差异再留言以征得您的同意。
